### ISSUE TITLE
Не плохой виджет, но написать vidget вместо widget это ...

### ISSUE THREAD

**Issue by bologer** [devlev/tc#1]
Поправьте пока вы еще только развиваетесь, `vidget` на `widget` и не позорьтесь.

```js
window.tolstoycomments.vidget.close();
```
на
```js
window.tolstoycomments.widget.close();
```

**Comment by devlev** [comment]
Спасибо за замечание! Исправим на widget. А в апи будем поддерживать оба варианта для поддержки текущих клиентов

**Comment by bologer** [comment]
@devlev не за что. Да, иначе сломается
